### ISSUE TITLE
known issue: react router + flask serving setup

### ISSUE THREAD

**Issue by Mattwmaster58** [CMPUT404W23-bigger-yoshi/CMPUT404-project-socialdistribution#59]
navigating in the frontend works fine, but directly navigation to URL 404's. known issue with known fix

**Comment by shehraj123** [comment]
I tried to fix routing in database branch for testing. Turns out you do have to remove the second "/authors" in user __init__.py for correct routing. Flask endpoints work in database branch now.

**Comment by Mattwmaster58** [comment]
tangentially related to #41

see for a better description of the problem and solution: https://stackoverflow.com/questions/30620276/flask-and-react-routing
